In [1]:
import init

from analisys.bkt_analisys import *
from analisys.data_analisys import *
from analisys.graph_analisys import *
from analisys.optmizer_analisys import *
from backend.mt5_tools import *

import pandas as pd

In [ ]:
cantrade = True

In [2]:
#usar na data da ultima segunda-feira

def fii_filter(fii_list_file = 'symbols_fiis.csv', filter = 50000):
    
    hist = mt5_historicaldata_s(60, '2021.11.05', '2021.11.13', csv_list= fii_list_file, reframe=False, print_ticker=False)

    key_raw_list = hist.keys()
    key_new_list = []

    for k in key_raw_list:
        if(np.sum(hist[k]['realvolume'])/5 > filter):
            key_new_list.append(k)

    
    return key_new_list
    
def spread(fii_symbol):
    bid, ask = mt5_currentprice(fii_symbol)
    return round(ask-bid,3)

In [3]:
hist = fii_filter()

In [4]:
fii_list = {'fii':[], 'spread':[], 'bid':[], 'ask':[]}

for i in hist:
    bid, ask = mt5_currentprice(i)

    fii_list['fii'].append(i)
    fii_list['spread'].append(spread(i))
    fii_list['bid'].append(round(bid, 3))
    fii_list['ask'].append(round(ask, 3))

fii_list = pd.DataFrame(fii_list)

In [5]:
fii_list

       fii  spread     bid     ask
0   BLMR11    0.02    7.58    7.60
1   CARE11    0.04    1.91    1.95
2   CPTS11    0.01   97.98   97.99
3   DEVA11    0.07  101.30  101.37
4   BRCR11    0.08   70.52   70.60
5   BCFF11    0.12   68.81   68.93
6   RECR11    0.01  100.08  100.09
7   TGAR11    0.24  120.56  120.80
8   CVBI11    0.35  101.51  101.86
9   MCCI11    0.10  103.00  103.10
10  IRDM11    0.02  107.07  107.09
11  HCTR11    0.08  123.67  123.75
12  KISU11    0.01    8.06    8.07
13  KNIP11    0.04  103.25  103.29
14  KNCR11    0.09  101.90  101.99
15  MXRF11    0.01    9.94    9.95
16  TORD11    0.03    9.52    9.55
17  TRXF11    0.10  101.19  101.29
18  VGHF11    0.01   10.08   10.09
19  VSLH11    0.01    9.55    9.56
20  XPLG11    0.04   97.23   97.27

In [61]:
_sfii = pd.DataFrame({'index':[], 'bool':[]})
_spread = pd.DataFrame(fii_list['spread'] > 0.10)
_sfii['bool'] = list(_spread['spread'])
_sfii['index'] = [i for i in range(0, len(_spread['spread']))]
_sfii.index = _sfii['index']
_sfii= _sfii.drop(columns=['index'])

_sfii = pd.DataFrame(_sfii)

for i in list(_sfii.index):
    if(_sfii['bool'][i] == False):
        fii_list = fii_list.drop(i)


fii_list.reset_index()

      fii  spread     bid     ask
5  BCFF11    0.12   68.81   68.93
7  TGAR11    0.24  120.56  120.80
8  CVBI11    0.35  101.51  101.86